meta:
  generated_ns: 1777716982360922413
  map_frame: map
  tf_ready_source_frame: gimbal_world
  reference_frame: map
  area_header_file: /home/hustlyrm/ros2_ly_ws_sentry/src/behavior_tree/module/Area.hpp
points:
  - name: Home.red
    original_cm: {x: 393, y: 810}
    transformed_cm: {x: 393, y: 810}
    delta_cm: {dx: 0, dy: 0}
  - name: Home.blue
    original_cm: {x: 2408, y: 683}
    transformed_cm: {x: 2408, y: 683}
    delta_cm: {dx: 0, dy: 0}
  - name: Base.red
    original_cm: {x: 401, y: 691}
    transformed_cm: {x: 401, y: 691}
    delta_cm: {dx: 0, dy: 0}
  - name: Base.blue
    original_cm: {x: 2400, y: 811}
    transformed_cm: {x: 2400, y: 811}
    delta_cm: {dx: 0, dy: 0}
  - name: Recovery.red
    original_cm: {x: 183, y: 245}
    transformed_cm: {x: 183, y: 245}
    delta_cm: {dx: 0, dy: 0}
  - name: Recovery.blue
    original_cm: {x: 2619, y: 1249}
    transformed_cm: {x: 2619, y: 1249}
    delta_cm: {dx: 0, dy: 0}
  - name: BuffShoot.red
    original_cm: {x: 924, y: 1388}
    transformed_cm: {x: 924, y: 1388}
    delta_cm: {dx: 0, dy: 0}
  - name: BuffShoot.blue
    original_cm: {x: 1872, y: 115}
    transformed_cm: {x: 1872, y: 115}
    delta_cm: {dx: 0, dy: 0}
  - name: LeftHighLand.red
    original_cm: {x: 406, y: 1332}
    transformed_cm: {x: 406, y: 1332}
    delta_cm: {dx: 0, dy: 0}
  - name: LeftHighLand.blue
    original_cm: {x: 2392, y: 187}
    transformed_cm: {x: 2392, y: 187}
    delta_cm: {dx: 0, dy: 0}
  - name: CastleLeft.red
    original_cm: {x: 657, y: 952}
    transformed_cm: {x: 657, y: 952}
    delta_cm: {dx: 0, dy: 0}
  - name: CastleLeft.blue
    original_cm: {x: 2136, y: 542}
    transformed_cm: {x: 2136, y: 542}
    delta_cm: {dx: 0, dy: 0}
  - name: Castle.red
    original_cm: {x: 666, y: 749}
    transformed_cm: {x: 666, y: 749}
    delta_cm: {dx: 0, dy: 0}
  - name: Castle.blue
    original_cm: {x: 2132, y: 749}
    transformed_cm: {x: 2132, y: 749}
    delta_cm: {dx: 0, dy: 0}
  - name: CastleRight1.red
    original_cm: {x: 505, y: 497}
    transformed_cm: {x: 505, y: 497}
    delta_cm: {dx: 0, dy: 0}
  - name: CastleRight1.blue
    original_cm: {x: 2293, y: 1014}
    transformed_cm: {x: 2293, y: 1014}
    delta_cm: {dx: 0, dy: 0}
  - name: CastleRight2.red
    original_cm: {x: 831, y: 509}
    transformed_cm: {x: 831, y: 509}
    delta_cm: {dx: 0, dy: 0}
  - name: CastleRight2.blue
    original_cm: {x: 1971, y: 985}
    transformed_cm: {x: 1971, y: 985}
    delta_cm: {dx: 0, dy: 0}
  - name: FlyRoad.red
    original_cm: {x: 868, y: 80}
    transformed_cm: {x: 868, y: 80}
    delta_cm: {dx: 0, dy: 0}
  - name: FlyRoad.blue
    original_cm: {x: 1929, y: 1402}
    transformed_cm: {x: 1929, y: 1402}
    delta_cm: {dx: 0, dy: 0}
  - name: OutpostArea.red
    original_cm: {x: 1138, y: 431}
    transformed_cm: {x: 1138, y: 431}
    delta_cm: {dx: 0, dy: 0}
  - name: OutpostArea.blue
    original_cm: {x: 1635, y: 1079}
    transformed_cm: {x: 1635, y: 1079}
    delta_cm: {dx: 0, dy: 0}
  - name: MidShoot.red
    original_cm: {x: 1075, y: 898}
    transformed_cm: {x: 1075, y: 898}
    delta_cm: {dx: 0, dy: 0}
  - name: MidShoot.blue
    original_cm: {x: 1702, y: 609}
    transformed_cm: {x: 1702, y: 609}
    delta_cm: {dx: 0, dy: 0}
  - name: LeftShoot.red
    original_cm: {x: 1165, y: 1063}
    transformed_cm: {x: 1165, y: 1063}
    delta_cm: {dx: 0, dy: 0}
  - name: LeftShoot.blue
    original_cm: {x: 1644, y: 476}
    transformed_cm: {x: 1644, y: 476}
    delta_cm: {dx: 0, dy: 0}
  - name: OutpostShoot.red
    original_cm: {x: 1393, y: 1047}
    transformed_cm: {x: 1393, y: 1047}
    delta_cm: {dx: 0, dy: 0}
  - name: OutpostShoot.blue
    original_cm: {x: 1434, y: 497}
    transformed_cm: {x: 1434, y: 497}
    delta_cm: {dx: 0, dy: 0}
  - name: BuffAround1.red
    original_cm: {x: 1372, y: 952}
    transformed_cm: {x: 1372, y: 952}
    delta_cm: {dx: 0, dy: 0}
  - name: BuffAround1.blue
    original_cm: {x: 1459, y: 530}
    transformed_cm: {x: 1459, y: 530}
    delta_cm: {dx: 0, dy: 0}
  - name: BuffAround2.red
    original_cm: {x: 1203, y: 770}
    transformed_cm: {x: 1203, y: 770}
    delta_cm: {dx: 0, dy: 0}
  - name: BuffAround2.blue
    original_cm: {x: 1591, y: 753}
    transformed_cm: {x: 1591, y: 753}
    delta_cm: {dx: 0, dy: 0}
  - name: RightShoot.red
    original_cm: {x: 1240, y: 559}
    transformed_cm: {x: 1240, y: 559}
    delta_cm: {dx: 0, dy: 0}
  - name: RightShoot.blue
    original_cm: {x: 1549, y: 923}
    transformed_cm: {x: 1549, y: 923}
    delta_cm: {dx: 0, dy: 0}
  - name: HoleRoad.red
    original_cm: {x: 1074, y: 1249}
    transformed_cm: {x: 1074, y: 1249}
    delta_cm: {dx: 0, dy: 0}
  - name: HoleRoad.blue
    original_cm: {x: 1677, y: 204}
    transformed_cm: {x: 1677, y: 204}
    delta_cm: {dx: 0, dy: 0}
  - name: OccupyArea.red
    original_cm: {x: 1075, y: 898}
    transformed_cm: {x: 1075, y: 898}
    delta_cm: {dx: 0, dy: 0}
  - name: OccupyArea.blue
    original_cm: {x: 1702, y: 609}
    transformed_cm: {x: 1702, y: 609}
    delta_cm: {dx: 0, dy: 0}
  - name: Highland.red
    original_cm: {x: 744, y: 1263}
    transformed_cm: {x: 744, y: 1263}
    delta_cm: {dx: 0, dy: 0}
  - name: Highland.blue
    original_cm: {x: 2056, y: 237}
    transformed_cm: {x: 2056, y: 237}
    delta_cm: {dx: 0, dy: 0}
