#!/usr/bin/env python3
"""Generate a source-backed Obsidian navigation layer for this ROS2 workspace."""

from __future__ import annotations

import argparse
import json
import re
import sys
import xml.etree.ElementTree as element_tree
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath
from typing import Iterable


GENERATED_MARKER = "<!-- GENERATED BY scripts/obsidian_sync.py; DO NOT EDIT -->\n"
MANIFEST_NAME = ".manifest.json"
TOPIC_RE = re.compile(r"(?<![A-Za-z0-9_])(/ly(?:/[A-Za-z0-9_]+)+)")
SOURCE_SUFFIXES = {".c", ".cc", ".cpp", ".cxx", ".h", ".hpp", ".py", ".xml", ".yaml", ".yml"}
DEPENDENCY_TAGS = {"depend", "build_depend", "buildtool_depend", "build_export_depend", "exec_depend", "test_depend"}


@dataclass(frozen=True)
class PackageInfo:
    name: str
    description: str
    path: PurePosixPath
    dependencies: tuple[str, ...]
    messages: dict[str, list[str]]
    source_files: tuple[PurePosixPath, ...]


@dataclass
class TopicInfo:
    name: str
    packages: set[str] = field(default_factory=set)
    source_files: set[PurePosixPath] = field(default_factory=set)


@dataclass(frozen=True)
class WorkspaceIndex:
    packages: dict[str, PackageInfo]
    topics: dict[str, TopicInfo]


@dataclass(frozen=True)
class SyncResult:
    is_current: bool
    planned_writes: int
    planned_deletes: int
    conflicts: tuple[PurePosixPath, ...]


def vault_link(path: PurePosixPath, label: str | None = None) -> str:
    """Return a repository-root-relative Obsidian wikilink."""
    target = path.with_suffix("").as_posix() if path.suffix == ".md" else path.as_posix()
    return f"[[{target}|{label or path.name}]]"


def topic_note_path(topic: str) -> PurePosixPath:
    return PurePosixPath("_generated", "Topics", topic.strip("/").replace("/", "__") + ".md")


def package_note_path(package: str) -> PurePosixPath:
    return PurePosixPath("_generated", "Packages", package + ".md")


def message_note_path(package: str, message: str) -> PurePosixPath:
    return PurePosixPath("_generated", "Messages", package, message + ".md")


def read_message_fields(path: Path) -> list[str]:
    fields: list[str] = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        field = line.split("#", maxsplit=1)[0].strip()
        if field:
            fields.append(field)
    return fields


def candidate_source_files(package_root: Path) -> Iterable[Path]:
    for path in sorted(package_root.rglob("*")):
        if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES:
            yield path


def is_dynamic_topic_prefix(content: str, match_end: int) -> bool:
    """Exclude a quoted topic prefix that source code concatenates at runtime."""
    line_end = content.find("\n", match_end)
    suffix = content[match_end : None if line_end == -1 else line_end]
    return bool(re.match(r"\s*[\"']?\s*(?:\+|<<)", suffix))


def collect_workspace(root: Path) -> WorkspaceIndex:
    """Read ROS packages and source-owned `/ly/...` topic occurrences."""
    root = root.resolve()
    packages: dict[str, PackageInfo] = {}
    topics: dict[str, TopicInfo] = {}
    for manifest in sorted((root / "src").glob("*/package.xml")):
        package_root = manifest.parent
        try:
            xml_root = element_tree.parse(manifest).getroot()
        except element_tree.ParseError as error:
            raise ValueError(f"Invalid package manifest: {manifest}") from error
        package_name = (xml_root.findtext("name") or "").strip()
        if not package_name:
            raise ValueError(f"Package manifest has no name: {manifest}")
        if package_name in packages:
            raise ValueError(f"Duplicate package name: {package_name}")
        messages = {
            message_file.stem: read_message_fields(message_file)
            for message_file in sorted((package_root / "msg").glob("*.msg"))
        }
        source_files = tuple(
            PurePosixPath(path.relative_to(root).as_posix()) for path in candidate_source_files(package_root)
        )
        dependencies = tuple(
            sorted(
                {
                    (element.text or "").strip()
                    for element in xml_root
                    if element.tag in DEPENDENCY_TAGS and (element.text or "").strip()
                }
            )
        )
        packages[package_name] = PackageInfo(
            name=package_name,
            description=(xml_root.findtext("description") or "").strip(),
            path=PurePosixPath(package_root.relative_to(root).as_posix()),
            dependencies=dependencies,
            messages=messages,
            source_files=source_files,
        )
        for source_file in source_files:
            source_path = root / source_file
            content = source_path.read_text(encoding="utf-8", errors="replace")
            for match in TOPIC_RE.finditer(content):
                if is_dynamic_topic_prefix(content, match.end()):
                    continue
                topic = match.group(1)
                info = topics.setdefault(topic, TopicInfo(name=topic))
                info.packages.add(package_name)
                info.source_files.add(source_file)
    return WorkspaceIndex(
        packages=dict(sorted(packages.items())),
        topics=dict(sorted(topics.items())),
    )


def render_workspace(
    index: WorkspaceIndex, vault_prefix: PurePosixPath = PurePosixPath("docs/obsidian")
) -> dict[PurePosixPath, str]:
    """Render deterministic generated notes, keyed relative to the vault directory."""
    pages: dict[PurePosixPath, str] = {}
    package_links = [
        f"- {vault_link(vault_prefix / package_note_path(name), name)}"
        for name in sorted(index.packages)
    ]
    topic_links = [
        f"- {vault_link(vault_prefix / topic_note_path(name), name)}" for name in sorted(index.topics)
    ]
    message_links = [
        f"- {vault_link(vault_prefix / message_note_path(package.name, message), package.name + '/' + message)}"
        for package in index.packages.values()
        for message in sorted(package.messages)
    ]
    pages[PurePosixPath("_generated/Index.md")] = GENERATED_MARKER + """---
tags:
  - generated
  - ros2
---

# 原始碼自動索引

此索引由 `package.xml`、`.msg` 與各 package 下的 source／launch／config 檔生成。修改來源後請在 repository root 執行 `python3 scripts/obsidian_sync.py`。

## ROS packages

""" + "\n".join(package_links) + "\n\n## /ly topics\n\n" + "\n".join(topic_links) + "\n\n## Messages\n\n" + "\n".join(message_links) + "\n"

    for package in index.packages.values():
        dependency_links = "\n".join(f"- `{dependency}`" for dependency in package.dependencies) or "- （無 manifest dependency）"
        message_links_for_package = "\n".join(
            f"- {vault_link(vault_prefix / message_note_path(package.name, message), message)}"
            for message in sorted(package.messages)
        ) or "- （無本地 `.msg`）"
        topics_for_package = [topic for topic, info in index.topics.items() if package.name in info.packages]
        package_topic_links = "\n".join(
            f"- {vault_link(vault_prefix / topic_note_path(topic), topic)}" for topic in topics_for_package
        ) or "- （未在掃描範圍內發現 `/ly/...` 字串）"
        pages[package_note_path(package.name)] = GENERATED_MARKER + f"""---
tags:
  - generated
  - ros-package
package: {package.name}
---

# {package.name}

{package.description or "（package.xml 未提供 description）"}

## 來源

- {vault_link(package.path / "package.xml", "package.xml")}

## Manifest dependencies

{dependency_links}

## Messages

{message_links_for_package}

## 掃描到的 /ly topics

{package_topic_links}
"""

        for message, fields in sorted(package.messages.items()):
            field_lines = "\n".join(f"- `{field}`" for field in fields) or "- （空 message）"
            pages[message_note_path(package.name, message)] = GENERATED_MARKER + f"""---
tags:
  - generated
  - ros-message
package: {package.name}
message: {message}
---

# {package.name}/{message}

## 來源

- {vault_link(package.path / "msg" / f"{message}.msg", f"{message}.msg")}
- {vault_link(vault_prefix / package_note_path(package.name), package.name)}

## Fields

{field_lines}
"""

    for topic, info in index.topics.items():
        owner_links = "\n".join(
            f"- {vault_link(vault_prefix / package_note_path(package), package)}" for package in sorted(info.packages)
        )
        source_links = "\n".join(
            f"- {vault_link(source, source.as_posix())}" for source in sorted(info.source_files)
        )
        pages[topic_note_path(topic)] = GENERATED_MARKER + f"""---
tags:
  - generated
  - ros-topic
topic: {topic}
---

# `{topic}`

此 note 只記錄本倉 source／launch／config 的字串出現位置；發布者／訂閱者語義仍須回到來源與正式文件確認。

## Related packages

{owner_links}

## Source occurrences

{source_links}
"""

    pages[PurePosixPath("_generated/Reports/sync-report.md")] = GENERATED_MARKER + f"""# 同步範圍報告

- ROS packages：{len(index.packages)}
- 本地 messages：{sum(len(package.messages) for package in index.packages.values())}
- `/ly/...` topic nodes：{len(index.topics)}

此報告是掃描計數，不取代 source review、launch composition 或目前 `docs/` 文件的架構說明。
"""
    return pages


def is_managed_relative_path(path: PurePosixPath) -> bool:
    return path.parts[:1] == ("_generated",) and ".." not in path.parts and path.name != MANIFEST_NAME


def is_safe_managed_target(
    generated_root: Path, output: Path, relative: PurePosixPath, *, allow_manifest: bool = False
) -> bool:
    """Reject symlinks and traversal that would make a generated write leave its owner tree."""
    if not is_managed_relative_path(relative) and not (
        allow_manifest and relative == PurePosixPath("_generated") / MANIFEST_NAME
    ):
        return False
    target = output / relative
    try:
        if not target.resolve(strict=False).is_relative_to(generated_root.resolve(strict=False)):
            return False
        current = generated_root
        for part in target.relative_to(generated_root).parts:
            current /= part
            if current.is_symlink():
                return False
        return True
    except OSError:
        return False


def read_manifest(path: Path) -> tuple[set[PurePosixPath], set[PurePosixPath]]:
    if not path.is_file():
        return set(), set()
    try:
        content = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise ValueError(f"Invalid generated manifest: {path}") from error
    files = content.get("files")
    if not isinstance(files, list) or not all(isinstance(item, str) for item in files):
        raise ValueError(f"Invalid generated manifest file list: {path}")
    parsed = {PurePosixPath(item) for item in files}
    return {item for item in parsed if is_managed_relative_path(item)}, {
        item for item in parsed if not is_managed_relative_path(item)
    }


def generated_manifest_content(files: set[PurePosixPath]) -> str:
    return json.dumps({"generator": "scripts/obsidian_sync.py", "files": [path.as_posix() for path in sorted(files)]}, ensure_ascii=False, indent=2) + "\n"


def sync(root: Path, output: Path, *, check: bool, dry_run: bool) -> SyncResult:
    """Synchronize only the generator-owned subtree, preserving human content."""
    root = root.resolve()
    output = output.resolve()
    expected_output = (root / "docs" / "obsidian").resolve()
    if output != expected_output:
        raise ValueError("--output must be exactly <repo-root>/docs/obsidian")
    try:
        vault_prefix = PurePosixPath(output.relative_to(root).as_posix())
    except ValueError as error:
        raise ValueError("--output must be inside --repo-root so Obsidian links remain portable") from error
    expected = render_workspace(collect_workspace(root), vault_prefix)
    generated_root = output / "_generated"
    manifest_path = generated_root / MANIFEST_NAME
    manifest_relative = PurePosixPath("_generated") / MANIFEST_NAME
    if generated_root.is_symlink() or not is_safe_managed_target(
        generated_root, output, manifest_relative, allow_manifest=True
    ):
        return SyncResult(False, 0, 0, (PurePosixPath("_generated"),))
    previous, invalid_manifest_paths = read_manifest(manifest_path)
    expected_paths = set(expected)
    writes: dict[PurePosixPath, str] = {}
    deletes: set[PurePosixPath] = set()
    conflicts: set[PurePosixPath] = set(invalid_manifest_paths)

    for relative, content in expected.items():
        target = output / relative
        if not is_safe_managed_target(generated_root, output, relative):
            conflicts.add(relative)
        elif target.exists() and not target.read_text(encoding="utf-8", errors="replace").startswith(GENERATED_MARKER):
            conflicts.add(relative)
        elif not target.is_file() or target.read_text(encoding="utf-8", errors="replace") != content:
            writes[relative] = content
    for relative in previous - expected_paths:
        target = output / relative
        if not is_safe_managed_target(generated_root, output, relative):
            conflicts.add(relative)
        elif not target.exists():
            continue
        if target.is_file() and target.read_text(encoding="utf-8", errors="replace").startswith(GENERATED_MARKER):
            deletes.add(relative)
        else:
            conflicts.add(relative)

    managed = expected_paths - conflicts
    manifest_content = generated_manifest_content(managed)
    if not manifest_path.is_file() or manifest_path.read_text(encoding="utf-8", errors="replace") != manifest_content:
        writes[PurePosixPath("_generated") / MANIFEST_NAME] = manifest_content

    preview = SyncResult(
        is_current=not writes and not deletes and not conflicts,
        planned_writes=len(writes),
        planned_deletes=len(deletes),
        conflicts=tuple(sorted(conflicts)),
    )
    if check or dry_run:
        return preview

    for relative in sorted(deletes, reverse=True):
        (output / relative).unlink()
    for relative, content in sorted(writes.items()):
        target = output / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    return SyncResult(
        is_current=not conflicts,
        planned_writes=preview.planned_writes,
        planned_deletes=preview.planned_deletes,
        conflicts=preview.conflicts,
    )


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate the source-backed Obsidian knowledge vault.")
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--output", type=Path, help="Vault subdirectory; defaults to <repo-root>/docs/obsidian.")
    parser.add_argument("--check", action="store_true", help="Report drift without writing generated notes.")
    parser.add_argument("--dry-run", action="store_true", help="Show planned changes without writing generated notes.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = args.repo_root.resolve()
    output = (args.output if args.output is not None else root / "docs" / "obsidian").resolve()
    if output != (root / "docs" / "obsidian").resolve():
        print("obsidian sync failed: --output must be exactly <repo-root>/docs/obsidian", file=sys.stderr)
        return 2
    try:
        result = sync(root, output, check=args.check, dry_run=args.dry_run)
    except (OSError, ValueError) as error:
        print(f"obsidian sync failed: {error}", file=sys.stderr)
        return 2
    action = "check" if args.check else "dry-run" if args.dry_run else "sync"
    print(f"obsidian {action}: writes={result.planned_writes} deletes={result.planned_deletes} conflicts={len(result.conflicts)}")
    for conflict in result.conflicts:
        print(f"conflict (preserved): {conflict}")
    return 0 if result.is_current else 1


if __name__ == "__main__":
    raise SystemExit(main())
